import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
const TeamStoryContent = () => {
    const paragraphs = [
        "In the autumn of 2023, four tech-enthusiastic architects and engineers found themselves sharing a common frustration: the construction industry's low level of digitalization. A few years into our careers, we were ready for change.",
        _jsxs(_Fragment, { children: ["We crossed paths at IAAC's Master in Advanced Computation for Architecture & Design (", _jsx("a", { href: "https://iaac.net/masters/master-in-advanced-computation-for-architecture-design/", target: "_blank", rel: "noopener noreferrer", className: "primary-link", children: "MaCAD" }), "), where Stasja taught a course in ML algorithms that we studied. Together, we developed several promising machine learning prototypes, including a daylight predictive model that was published in a ", _jsx("a", { href: "https://www.sciencedirect.com/science/article/abs/pii/S0360132325002252", target: "_blank", rel: "noopener noreferrer", className: "primary-link", children: "high-impact journal" }), "."] }),
        _jsxs(_Fragment, { children: ["This success sparked an idea: why not adapt this model for Swedish regulations? We applied for funding and received two grants from the ", _jsx("a", { href: "https://belysningsstiftelsen.se/projekt/alejandro-pacheco-dieguez-ml-modell-for-dagsljusanalys", target: "_blank", rel: "noopener noreferrer", className: "primary-link", children: "Bertil and Britt Svensson Foundation" }), ". The project has been generating ", _jsx("a", { href: "https://www.svenskbyggtidning.se/2025/03/21/nytt-ai-projekt-satter-dagsljuset-i-fokus/", target: "_blank", rel: "noopener noreferrer", className: "primary-link", children: "buzz" }), " in the industry, and after a couple of months working together, we've discovered something even more valuable: we make a great team. ", _jsx("a", { href: "https://www.almi.se/", target: "_blank", rel: "noopener noreferrer", className: "primary-link", children: "Almi" }), ", Sweden's business development agency, thinks so too. "] }),
        _jsxs(_Fragment, { children: ["No bs and no buzzwords, effectiveness and transparency are values that we found in common, no matter the project we are working on. We want to understand the problem and provide a solution that works, not just a fancy tool that looks good on paper. Does it resonate?", _jsx("a", { href: "mailto:info@upskiller.xyz", target: "_blank", rel: "noopener noreferrer", className: "primary-link", children: " Reach out" }), " to us, we love virtual coffee chats.\""] }),
    ];
    return (_jsx(_Fragment, { children: paragraphs.map((para, idx) => (_jsx("p", { className: "team-paragraph", children: para }, idx))) }));
};
export default TeamStoryContent;
