import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { SharedButton } from './SharedButton';
const InfoCard = ({ title, subtitle, problem, description, items, itemsLabel = "Key Features:", icon, buttonText, buttonDisabled = false, buttonStyle, onClick, onButtonClick, className = '', style = { backgroundColor: '#00d67a' }, showButton = true }) => {
    const defaultButtonStyle = { backgroundColor: buttonDisabled ? '#33de95' : '#00ff66' };
    const finalButtonStyle = { ...defaultButtonStyle, ...buttonStyle };
    return (_jsx("div", { className: `p-8 shadow-sm hover:shadow-lg transition-all duration-300 ${className}`, style: style, onClick: onClick, children: _jsxs("div", { className: "space-y-6", children: [icon && (_jsx("div", { className: "flex items-start justify-between", children: _jsx("div", { className: "w-16 h-16 bg-primary-100 rounded-xl flex items-center justify-center text-primary-600", children: icon }) })), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { children: [_jsx("h3", { className: `font-heading font-bold text-dark ${subtitle ? 'text-3xl' : 'text-2xl'}`, children: title }), subtitle && (_jsx("p", { className: "text-lg text-dark font-medium", children: subtitle }))] }), problem && (_jsxs("p", { className: "text-dark leading-relaxed", children: [_jsx("strong", { children: "Problem:" }), " ", problem] })), _jsxs("p", { className: "text-dark leading-relaxed", children: [_jsx("strong", { children: "Solution:" }), " ", description] })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("h4", { className: "font-medium text-dark", children: itemsLabel }), _jsx("div", { className: "space-y-2", children: items.map((item, index) => (_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("div", { className: "w-2 h-2 rounded-full", style: { backgroundColor: '#4e378a' } }), _jsx("span", { className: "text-sm text-dark", children: item })] }, index))) })] }), showButton && buttonText && (_jsx("div", { style: finalButtonStyle, children: _jsx(SharedButton, { variant: "contact", className: "w-full", onClick: onButtonClick, disabled: buttonDisabled, children: buttonText }) }))] }) }));
};
export { InfoCard };
export default InfoCard;
